/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.cien.client;

import java.awt.Desktop;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.IOException;
import java.net.URISyntaxException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.AbstractListModel;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.event.HyperlinkEvent;
import javax.swing.text.DefaultCaret;
import javax.swing.text.html.HTMLDocument;

/**
 *
 * @author Cien
 */
public class Chat extends javax.swing.JFrame {

    /**
     * Creates new form Chat
     */
    public Chat() {
        initComponents();
        start();
    }

    private void start() {
        setLocationRelativeTo(null);
        ((DefaultCaret) textPane.getCaret()).setUpdatePolicy(DefaultCaret.ALWAYS_UPDATE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        groupUserList = new javax.swing.JList<>();
        textField = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        groupList = new javax.swing.JList<>();
        newGroupButton = new javax.swing.JButton();
        enterGroupButton = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        textPane = new javax.swing.JTextPane();
        uploadImageButton = new javax.swing.JButton();
        exitGroup = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Chat do Cien");
        setResizable(false);

        jScrollPane1.setViewportView(groupUserList);

        textField.setEnabled(false);

        jScrollPane3.setViewportView(groupList);

        newGroupButton.setText("Novo Grupo");

        enterGroupButton.setText("Entrar em Grupo");

        textPane.setEditable(false);
        textPane.setContentType("text/html"); // NOI18N
        textPane.setText("<p style=\"margin-top: 0;\">Entre, crie ou escolha um grupo!</p>\n");
        textPane.addHyperlinkListener(new javax.swing.event.HyperlinkListener() {
            public void hyperlinkUpdate(javax.swing.event.HyperlinkEvent evt) {
                textPaneHyperlinkUpdate(evt);
            }
        });
        jScrollPane4.setViewportView(textPane);

        uploadImageButton.setEnabled(false);

        exitGroup.setText("Sair do Grupo");
        exitGroup.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(enterGroupButton, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(newGroupButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(exitGroup, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(textField, javax.swing.GroupLayout.DEFAULT_SIZE, 268, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(uploadImageButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(newGroupButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(enterGroupButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane3))
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 233, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(textField)
                                .addComponent(exitGroup))
                            .addComponent(uploadImageButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );

        try {      uploadImageButton.setIcon(  new ImageIcon(  new ImageIcon(  Chat.class.getResource("image.png")  ).getImage().getScaledInstance(16, 16, Image.SCALE_SMOOTH)  )  );  } catch (Exception ex){}

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textPaneHyperlinkUpdate(javax.swing.event.HyperlinkEvent evt) {//GEN-FIRST:event_textPaneHyperlinkUpdate
        if (evt.getEventType().equals(HyperlinkEvent.EventType.ACTIVATED)) {
            new Thread(() -> {
                try {
                    Desktop.getDesktop().browse(evt.getURL().toURI());
                } catch (URISyntaxException | IOException ex) {
                    Logger.getLogger(Chat.class.getName()).log(Level.SEVERE, null, ex);
                }
            }, "Open Link").start();
        }
    }//GEN-LAST:event_textPaneHyperlinkUpdate

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton enterGroupButton;
    private javax.swing.JButton exitGroup;
    private javax.swing.JList<String> groupList;
    private javax.swing.JList<String> groupUserList;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JButton newGroupButton;
    private javax.swing.JTextField textField;
    private javax.swing.JTextPane textPane;
    private javax.swing.JButton uploadImageButton;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the enterGroupButton
     */
    public javax.swing.JButton getEnterGroupButton() {
        return enterGroupButton;
    }

    /**
     * @return the groupList
     */
    public javax.swing.JList<String> getGroupList() {
        return groupList;
    }

    /**
     * @return the groupUserList
     */
    public javax.swing.JList<String> getGroupUserList() {
        return groupUserList;
    }

    /**
     * @return the newGroupButton
     */
    public javax.swing.JButton getNewGroupButton() {
        return newGroupButton;
    }

    /**
     * @return the textField
     */
    public javax.swing.JTextField getTextField() {
        return textField;
    }

    public JButton getExitGroup() {
        return exitGroup;
    }

    /**
     * @return the textPane
     */
    public javax.swing.JTextPane getTextPane() {
        return textPane;
    }

    /**
     * @return the uploadImageButton
     */
    public javax.swing.JButton getUploadImageButton() {
        return uploadImageButton;
    }

    @Override
    public void setVisible(boolean b) {
        super.setVisible(b);
        if (!b) {
            groupList.setModel(new DefaultListModel<>());
            textPane.setText("");
            textField.setText("");
            groupUserList.setModel(new DefaultListModel<>());
        }
    }

}
